<?php if ($this->flashMessages) : ?>
<div class="alert alert-success">
    <?=implode('<br>', $this->flashMessages)?>
</div>
<?php endif; ?>

<h2>Liste des contacts</h2>

<table class="table table-striped">
    <?php foreach ($this->contacts as $c) : ?>
    <tr>
        <td><?=$this->escapeHtml($c->getPrenom())?> <?=$this->escapeHtml($c->getNom())?></td>
        <td>
            <a href="<?=$this->url('contact/show', ['id' => $c->getId()])?>">Afficher</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>