<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?=$this->url(['controller'=>'index', 'action'=>'index'], null, true)?>">Address Book</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?=$this->url(['controller'=>'index', 'action'=>'index'], null, true)?>">Accueil</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contacts <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?=$this->url(['controller'=>'contact', 'action'=>'index'], null, true)?>">Lister</a></li>
                        <li><a href="<?=$this->url(['controller'=>'contact', 'action'=>'add'], null, true)?>">Ajouter</a></li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>