
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="author" content="">
        
        <?=$this->headMeta()?>

        <?=$this->headTitle('Address Book')->setSeparator(' - ')?>

        <!-- Bootstrap core CSS -->
        <link href="<?=$this->baseUrl('css/bootstrap.min.css')?>" rel="stylesheet">
        
        <?=$this->headLink()?>
        
        <?=$this->headStyle()?>
        
        <?=$this->headScript()?>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <?=$this->partial('_menu.phtml')?>

        <div class="container">

            <?php echo $this->layout()->content; ?>

        </div><!-- /.container -->


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="<?=$this->baseUrl('js/jquery-1.12.0.js')?>"></script>
        <script src="<?=$this->baseUrl('js/bootstrap.js')?>"></script>
        
        <?=$this->inlineScript()?>
    </body>
</html>

